### ISSUE TITLE
Anyhow, What does this program do?

### ISSUE THREAD

**Issue by biergaizi** [AOSC-Archive/Anthon-Starter#24]
I has joined this project and worked on some of the core features, but I have still no idea what the program does... In my opinion we need a feature specification and a roadmap to help developers to cooperate and work on this project.

**Comment by jyhi** [comment]
@biergaizi 

> I has joined this project and worked on some of the core features

Sincere thanks to you. :smiley: 

> but I have still no idea what the program does...

Sorry to hear that, but that's totally my wok. ~~Anthon-Starter is simply yet another [Deepin Windows Installer](https://github.com/linuxdeepin/deepin-windows-installer), but~~ messy codes may confuse you. We can have a talk about it.

> In my opinion we need a feature specification and a roadmap to help developers to cooperate and work on this project.

Yes we indeed need them, and we will have a deep discussion about the plan of Anthon-Starter on [AOSCC 2016](https://github.com/AOSC-Dev/aoscc/tree/master/2016). @liushuyu , @ekd123 , @m13253 (maybe) and me will be present (@biergaizi do you?). Once we've worked out some obvious things (???), we will update #18 and push forward this project. I hope you can still participate in this ~~actually enormous~~ project.

**Comment by liushuyu** [comment]
> actually enormous project.

No, terribly messy project.

**Comment by jyhi** [comment]
> terribly messy project.

So if we want to make it neater we should have a discussion on it.

**Comment by liushuyu** [comment]
> So if we want to make it neater we should have a discussion on it.

So, IMO we need to have a discussion ASAP

**Comment by liushuyu** [comment]
>So if we want to make it neater we should have a discussion on it.

So, IMO we need to have a discussion ASAP

**Comment by jyhi** [comment]
> So, IMO we need to have a discussion ASAP

On AOSCC day 3.

**Comment by MingcongBai** [comment]
Might I suggest a brief introduction by the end of Day 2 as part of the
kick-off activity for Day 3?
2016年7月3日 11:08，"Junde Yhi" notifications@github.com写道：

**Comment by jyhi** [comment]
> Might I suggest a brief introduction by the end of Day 2 as part of the kick-off activity for Day 3?

Yes. We'll do it.

**Comment by biergaizi** [comment]
I need all the discussions to be video-recorded.

**Comment by jyhi** [comment]
@biergaizi Video?🌚

**Comment by biergaizi** [comment]
Live-stream would be even better...

**Comment by StephDC** [comment]
I would provide a RTMP server for live-streaming and OBS for recording at the same time. The only equipment missing by now is a WebCam.
Sincerely,
SHUNRAN ZHANG

Sending people documents in Word format has bad effects, because that practice puts pressure on them to use Microsoft software. In effect, you become a buttress of the Microsoft monopoly. This specific problem is a major obstacle to the broader adoption of GNU/Linux. Would you please reconsider the use of Word format for communication with other people?

**Comment by MingcongBai** [comment]
> I would provide a RTMP server for live-streaming and OBS for recording at the same time. The only equipment missing by now is a WebCam.

Possibly wrong location for this comment? WebCam should be easy to get a hold of (you can even take mine if necessary). I can bring in a DSLR though if that's necessary.

**Comment by jyhi** [comment]
> biergaizi opened this Issue on 1 Jul 2016

Accidentally find this (still) opening issue.

It's been a year and a half, and things have changed a lot. About Anthon-Starter, there is actually a long history to tell.

At the very beginning, I intended to create an easy-to-use GUI installer for potential Anthon OS (later renamed as AOSC OS) users, since newbies may be scared by the complicated manual installation steps. However, at that time I had very limited experience on programming (yes, I just started application programming at that time; I programmed for [NOIP](http://www.noi.cn/) previously). Thus, I managed to write one using Delphi (only drag & drop work, plus copy & paste snippets) and Windows Batch (have written some scripts before). That was 0.1.0, the beginning of this project.

Because I _thought_ I was more skillful in Windows Batch, AnthonOS-Starter (at that time it was using this name) 0.1.x[^1] was written, completely using Windows Batch (of course, 7-Zip binaries to do extra work). At 0.1.2 Anthon-Starter (this time it was using this name[^2]) most of the goals have achieved, although it was totally broken in some ways (such as the FAKE SUPPORT of UEFI). Then after some time, I realized that coding in Windows Batch was not a modern way. By chance, I learned about C language. And then 0.2.0 was created, hence this repository. This is it.

So here I would like to answer the question: **what does this program do?** As I mentioned above, Anthon-Starter is **an easy-to-use (AOSC) Linux GUI installer on Windows**. It supports installing AOSC OS from Windows by one click **without using any external drives** (it alters the boot loader), and is planned to support more Linux distributions so that it can be a universal installer. Nevertheless,

> "The world's changed, Celia."
> _-- Tears of Stell (2012)_

In 2012 (umm, that was exactly the year when I started this project) there might be few easy-to-use Linux image writer, but now there are a lot. Modifying the boot loader on user's machine is a quite risky operation, and I can't even guarantee a basic usability. What's more, people have changed their mind; they do not keep using Windows to "bootstrap" a Linux distribution. Anthon-Starter loses its meaning. Plus the one-year interruption due to CEE, I have had no passion for working on it. In my opinion this project is at its end.

Plus: on AOSCC 2016, except for introduction and discussion on specific implementations, nothing else got promoted.

[^1]: I know that was not SemVer-ish.
[^2]:  Fun fact: the change of name was partially because @MingcongBai wrongly configured the category name list in bug tracker using "Anthon-Starter" (w/o "OS"). I looked at it, thought it was okay, and changed the project name.
