### ISSUE TITLE
Coverity Scan Static Analysis doesn't work

### ISSUE THREAD

**Issue by jyhi** [AOSC-Archive/Anthon-Starter#6]
Now Coverity Scan Static Analysis seems not to work. It always gives **"failed"** status, and it is abnormal.

Before switching to the official script, Coverity just broke when nothing changed. But now it doesn't work at all.

@liushuyu if you can, please fix it soon.

**Comment by liushuyu** [comment]
I just want to say this problem was not caused by me!!!! My API IS CORRECT!

## Coverity sent me an e-mail :

Your request for analysis of AOSC-Dev/Anthon-Starter is failed.
Analysis status: No action need

The problem is on the Coverity server, and we will address it.
Your request will be automatically submitted for analysis.

## If you do not see your build being analyzed, please email scan-admin@coverity.com.

At 2014-12-14 18:06:29, "Junde Yi" notifications@github.com wrote:

Now Coverity Scan Static Analysis seems not to work. It always gives "failed" status, and it is abnormal.

Before switching to the official script, Coverity just broke when nothing changed. But now it doesn't work at all.

@liushuyu if you can, please fix it soon.

**Comment by liushuyu** [comment]
I have solved this by writing an e-mail to their support center. They fixed that.

**Comment by jyhi** [comment]
@liushuyu Good job.
